version: '3.8'

services:
  redis-node-1:
    image: redis:7.2-alpine
    container_name: redis-node-1
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "7001:7001"
      - "17001:17001"
    volumes:
      - ./redis-config/redis-node-1.conf:/usr/local/etc/redis/redis.conf
      - redis-node-1-data:/data
    networks:
      - redis-cluster-net

  redis-node-2:
    image: redis:7.2-alpine
    container_name: redis-node-2
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "7002:7002"
      - "17002:17002"
    volumes:
      - ./redis-config/redis-node-2.conf:/usr/local/etc/redis/redis.conf
      - redis-node-2-data:/data
    networks:
      - redis-cluster-net

  redis-node-3:
    image: redis:7.2-alpine
    container_name: redis-node-3
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "7003:7003"
      - "17003:17003"
    volumes:
      - ./redis-config/redis-node-3.conf:/usr/local/etc/redis/redis.conf
      - redis-node-3-data:/data
    networks:
      - redis-cluster-net

  redis-node-4:
    image: redis:7.2-alpine
    container_name: redis-node-4
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "7004:7004"
      - "17004:17004"
    volumes:
      - ./redis-config/redis-node-4.conf:/usr/local/etc/redis/redis.conf
      - redis-node-4-data:/data
    networks:
      - redis-cluster-net

  redis-node-5:
    image: redis:7.2-alpine
    container_name: redis-node-5
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "7005:7005"
      - "17005:17005"
    volumes:
      - ./redis-config/redis-node-5.conf:/usr/local/etc/redis/redis.conf
      - redis-node-5-data:/data
    networks:
      - redis-cluster-net

  redis-node-6:
    image: redis:7.2-alpine
    container_name: redis-node-6
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "7006:7006"
      - "17006:17006"
    volumes:
      - ./redis-config/redis-node-6.conf:/usr/local/etc/redis/redis.conf
      - redis-node-6-data:/data
    networks:
      - redis-cluster-net

  redis-cluster-init:
    image: redis:7.2-alpine
    container_name: redis-cluster-init
    depends_on:
      - redis-node-1
      - redis-node-2
      - redis-node-3
      - redis-node-4
      - redis-node-5
      - redis-node-6
    networks:
      - redis-cluster-net
    command: >
      sh -c "sleep 5 &&
             redis-cli --cluster create 
             redis-node-1:7001 
             redis-node-2:7002 
             redis-node-3:7003 
             redis-node-4:7004 
             redis-node-5:7005 
             redis-node-6:7006 
             --cluster-replicas 1 
             --cluster-yes"

volumes:
  redis-node-1-data:
  redis-node-2-data:
  redis-node-3-data:
  redis-node-4-data:
  redis-node-5-data:
  redis-node-6-data:

networks:
  redis-cluster-net:
    driver: bridge